# -*- coding: utf-8 -*-
"""Audio_Cleaner 2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kdFhYG_eJHx84Qm-GlkM4wTLeqXXuPk1
"""

!pip install librosa soundfile scikit-learn matplotlib seaborn tqdm

from google.colab import drive
drive.mount('/content/drive')

import os

# ── Folder that contains ALL your .wav and .txt files ───────
DATASET_ROOT = "/content/drive/MyDrive/Button click dataset"   # ← change if needed

# ── Where to save model + normalisation params ───────────────
MODEL_SAVE_PATH = "/content/drive/MyDrive/audio_cleaner_lstm.h5"
NORM_MEAN_PATH  = "/content/drive/MyDrive/norm_mean.npy"
NORM_STD_PATH   = "/content/drive/MyDrive/norm_std.npy"

# ── Audio settings ───────────────────────────────────────────
SAMPLE_RATE    = 16000   # Hz – everything resampled to this
FRAME_DURATION = 0.025   # seconds per analysis frame  (25 ms)
HOP_DURATION   = 0.010   # seconds per hop             (10 ms)
N_MFCC         = 40      # MFCC coefficients

# ── Training settings ────────────────────────────────────────
TEST_SIZE      = 0.15
VAL_SIZE       = 0.15
BATCH_SIZE     = 32
EPOCHS         = 50
LEARNING_RATE  = 1e-3
MAX_TIMESTEPS  = 100     # ← Fixed frame sequence length for padding/truncating

# ── Class definitions ────────────────────────────────────────
CLASSES      = ["silence", "button_click", "speech"]
CLASS_TO_IDX = {c: i for i, c in enumerate(CLASSES)}

# Mapping from raw label text → canonical class name
LABEL_MAP = {
    "silence":      "silence",
    "button click": "button_click",
    "button_click": "button_click",
    "speech":       "speech",
}

print(" Config loaded. ")
print(f"   Dataset root    : {DATASET_ROOT}")
print(f"   Max Timesteps   : {MAX_TIMESTEPS} frames")
print(f"   Classes         : {CLASSES}")

import re
from pathlib import Path

def pair_files(dataset_root):
    """
    Returns a list of (wav_path, label_path) tuples.

    Naming convention:
        WAV  : KIKF1-000-00001.wav   (last segment is zero-padded index)
        Label: Labels 1.txt          (integer index, no zero-padding)
    """
    root   = Path(dataset_root)
    pairs  = []
    errors = []

    for wav_path in sorted(root.glob("*.wav")):
        # Extract the trailing numeric index from the wav stem
        # e.g. "KIKF1-000-00001" → "00001" → 1
        match = re.search(r'-(\d+)$', wav_path.stem)
        if not match:
            errors.append(f"Cannot parse index from: {wav_path.name}")
            continue

        idx        = int(match.group(1))          # strip leading zeros → int
        label_name = f"Labels {idx}.txt"
        label_path = root / label_name

        if label_path.exists():
            pairs.append((wav_path, label_path))
        else:
            errors.append(f"Missing label file: {label_name}  (for {wav_path.name})")

    if errors:
        print(" Pairing warnings: ")
        for e in errors:
            print(f"    {e}")

    print(f"Paired {len(pairs)} wav+label file(s).")
    return pairs

pairs = pair_files(DATASET_ROOT)

# Quick sanity-check — show first 5 pairs
print("\nFirst 5 pairs:")
for w, l in pairs[:5]:
    print(f"  {w.name}  →  {l.name}")

def parse_label_file(label_path):
    segments = []
    with open(label_path, "r") as f:
        for lineno, line in enumerate(f, 1):
            line = line.strip()
            if not line:
                continue
            parts = line.split("\t")
            if len(parts) != 3:
                print(f"Warning: Line {lineno} in {label_path.name} does not have 3 tab-separated parts: {line}")
                continue
            try:
                start = float(parts[0])
                end   = float(parts[1])
                raw   = parts[2].strip().lower()
                canonical = LABEL_MAP.get(raw)
                if canonical is None:
                    print(f"Warning: Unknown label '{raw}' in line {lineno} of {label_path.name}")
                    continue
                segments.append((start, end, CLASS_TO_IDX[canonical]))
            except ValueError:
                print(f"Warning: Could not parse start/end times in line {lineno} of {label_path.name}: {line}")
                continue
    return segments

import numpy as np
import librosa

def load_audio(path, sr=SAMPLE_RATE):
    y, _ = librosa.load(str(path), sr=sr, mono=True)
    return y

def augment_audio(y, sr=SAMPLE_RATE):
    """
    Applies random augmentations directly to the raw audio
    to force the model to learn structural invariance.
    """
    # 1. Random Pitch Shifting (-2 to +2 semitones)
    if np.random.rand() > 0.5:
        n_steps = np.random.uniform(-2.0, 2.0)
        y = librosa.effects.pitch_shift(y, sr=sr, n_steps=n_steps)

    # 2. Random Time Stretching (0.8x slower to 1.2x faster)
    if np.random.rand() > 0.5:
        rate = np.random.uniform(0.8, 1.2)
        y = librosa.effects.time_stretch(y, rate=rate)

    return y

def extract_mfcc_features(segment_audio, sr=SAMPLE_RATE):
    """
    Returns a (T, 120) sequence feature matrix (MFCCs + Delta + Delta-Delta)
    Without compressing the time dimension.
    """
    frame_len = int(sr * FRAME_DURATION)
    hop_len   = int(sr * HOP_DURATION)

    if len(segment_audio) < frame_len:
        segment_audio = np.pad(segment_audio, (0, frame_len - len(segment_audio)))

    mfcc   = librosa.feature.mfcc(y=segment_audio, sr=sr, n_mfcc=N_MFCC,
                                   n_fft=frame_len, hop_length=hop_len)
    delta  = librosa.feature.delta(mfcc)
    delta2 = librosa.feature.delta(mfcc, order=2)

    features = np.concatenate([mfcc, delta, delta2], axis=0).T  # Returns shape (T, 120)
    return features.astype(np.float32)

print("Advanced Feature extraction and Augmentation pipelines initialized.")

from tqdm.notebook import tqdm
from tensorflow.keras.preprocessing.sequence import pad_sequences

MIN_SEGMENT_DURATION = 0.02
X_list, y_list = [], []

for wav_path, label_path in tqdm(pairs, desc="Processing Audio Sequences"):
    try:
        audio    = load_audio(wav_path)
        segments = parse_label_file(label_path)
    except Exception as e:
        print(f" Skipping {wav_path.name}: {e} ")
        continue

    for (start, end, class_idx) in segments:
        duration = end - start
        if duration < MIN_SEGMENT_DURATION:
            continue

        start_sample = int(start * SAMPLE_RATE)
        end_sample   = int(end   * SAMPLE_RATE)
        seg_audio    = audio[start_sample:end_sample]

        # --- FIX 2: Apply Augmentation targeting the underperforming class ---
        if class_idx == CLASS_TO_IDX["button_click"]:
            # Inject original sample
            features = extract_mfcc_features(seg_audio)
            X_list.append(features)
            y_list.append(class_idx)

            # Synthesize an extra augmented variant to build generalization profile
            aug_audio = augment_audio(seg_audio)
            features_aug = extract_mfcc_features(aug_audio)
            X_list.append(features_aug)
            y_list.append(class_idx)
        else:
            features = extract_mfcc_features(seg_audio)
            X_list.append(features)
            y_list.append(class_idx)

# --- FIX 1: Apply temporal sequence padding and truncating ---
# Shorter matrices are padded with zeros, longer matrices are cut cleanly at MAX_TIMESTEPS.
X_padded = pad_sequences(X_list, maxlen=MAX_TIMESTEPS, dtype='float32',
                         padding='post', truncating='post')
y = np.array(y_list, dtype=np.int32)

print(f"\\n Temporal Dataset Built!")
print(f"   X Shape (Sequences): {X_padded.shape} -> (Samples, Timesteps, Features)")
print(f"   y Shape            : {y.shape}")

from sklearn.model_selection import train_test_split
import numpy as np # Ensure numpy is imported for empty array creation

if X_padded.shape[0] == 0:
    print(" Warning: X_padded is empty. Cannot perform train-test split. Please check previous cells for data loading and feature extraction issues.")
    # Initialize empty split arrays to prevent further errors if the notebook continues
    X_train, X_val, X_test = np.array([]), np.array([]), np.array([])
    y_train, y_val, y_test = np.array([]), np.array([]), np.array([])
    mean = np.array([])
    std = np.array([])
else:
    X_temp, X_test, y_temp, y_test = train_test_split(
        X_padded, y, test_size=TEST_SIZE, random_state=42, stratify=y)

    val_frac = VAL_SIZE / (1 - TEST_SIZE)
    X_train, X_val, y_train, y_val = train_test_split(
        X_temp, y_temp, test_size=val_frac, random_state=42, stratify=y_temp)

    # Scale over 3D array dimensions excluding the feature axis to prevent leak
    flat_X_train = X_train.reshape(-1, X_train.shape[-1])
    mean = flat_X_train.mean(axis=0, keepdims=True)
    std  = flat_X_train.std(axis=0, keepdims=True) + 1e-8

    # Normalize keeping sequential structures intact
    X_train = (X_train - mean) / std
    X_val   = (X_val - mean) / std
    X_test  = (X_test - mean) / std

    np.save(NORM_MEAN_PATH, mean)
    np.save(NORM_STD_PATH,  std)

    print(f" Sequence Splits — Train: {X_train.shape} | Val: {X_val.shape} | Test: {X_test.shape}")

import tensorflow as tf
from tensorflow.keras import layers, models, optimizers

n_features = X_train.shape[2] # 120
n_classes  = len(CLASSES)

def build_temporal_model(n_features, n_classes):
    # Notice: Shape accepts explicit temporal dimension sequence arrays now!
    inputs = layers.Input(shape=(MAX_TIMESTEPS, n_features), name="sequential_input")

    # Tracking frame transitions dynamically over the timeline
    x = layers.Bidirectional(
            layers.LSTM(128, return_sequences=True, dropout=0.3,
                        recurrent_dropout=0.2), name="bilstm_sequence_1")(inputs)
    x = layers.Bidirectional(
            layers.LSTM(64, return_sequences=False, dropout=0.3,
                        recurrent_dropout=0.2), name="bilstm_sequence_2")(x)

    x = layers.Dense(64, activation="relu")(x)
    x = layers.Dropout(0.4)(x)
    outputs = layers.Dense(n_classes, activation="softmax", name="class_probs")(x)

    model = models.Model(inputs, outputs)
    model.compile(
        optimizer=optimizers.Adam(LEARNING_RATE),
        loss="sparse_categorical_crossentropy",
        metrics=["accuracy"]
    )
    return model

model = build_temporal_model(n_features, n_classes)
model.summary()

from sklearn.utils.class_weight import compute_class_weight

# Rebalance loss evaluation due to class imbalances
class_weights = compute_class_weight('balanced', classes=np.unique(y_train), y=y_train)
class_weight_dict = {i: w for i, w in enumerate(class_weights)}

early_stop = tf.keras.callbacks.EarlyStopping(
    monitor='val_loss', patience=7, restore_best_weights=True, verbose=1
)

history = model.fit(
    X_train, y_train,
    validation_data=(X_val, y_val),
    batch_size=BATCH_SIZE,
    epochs=EPOCHS,
    class_weight=class_weight_dict,
    callbacks=[early_stop],
    verbose=1
)

import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(12, 4))
plt.subplot(1, 2, 1)
plt.plot(history.history['accuracy'], label='Train Accuracy')
plt.plot(history.history['val_accuracy'], label='Val Accuracy')
plt.title('Sequence Model Accuracy Evolution')
plt.xlabel('Epoch')
plt.ylabel('Accuracy')
plt.legend()

plt.subplot(1, 2, 2)
plt.plot(history.history['loss'], label='Train Loss')
plt.plot(history.history['val_loss'], label='Val Loss')
plt.title('Sequence Model Loss Curve Progression')
plt.xlabel('Epoch')
plt.ylabel('Loss')
plt.legend()
plt.show()

# ============================================================
# CELL 19 — Upload, Clean & Download Audio (WAV + MP3)
#
# Run this cell AFTER training (or after Cell 18 if reloading
# a saved model).  It will:
#   1. Pop up a file picker — accepts .wav OR .mp3 files
#   2. Run the LSTM cleaner on each uploaded file
#   3. Show a before/after waveform + label timeline
#   4. Let you play both clips inside the notebook
#   5. Auto-download the cleaned file as a .wav to your computer
# ============================================================

import os
import numpy as np
import librosa
import librosa.display
import soundfile as sf
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
import IPython.display as ipd
from pathlib import Path
from google.colab import files
from tensorflow.keras.preprocessing.sequence import pad_sequences # Import pad_sequences

# ── Paths ────────────────────────────────────────────────────
UPLOAD_DIR = "/content/uploaded_audio"
CLEAN_DIR  = "/content/cleaned_audio"
os.makedirs(UPLOAD_DIR, exist_ok=True)
os.makedirs(CLEAN_DIR,  exist_ok=True)

# ── Supported formats ─────────────────────────────────────────
SUPPORTED_EXTENSIONS = {".wav", ".mp3"}

# ────────────────────────────────────────────────────────────
# Helper: load audio — works for both WAV and MP3
# librosa.load() handles MP3 decoding automatically via audioread
# ────────────────────────────────────────────────────────────
def load_any_audio(path, sr=SAMPLE_RATE):
    """Load WAV or MP3 and return a mono float32 numpy array."""
    y, _ = librosa.load(str(path), sr=sr, mono=True)
    return y

# ────────────────────────────────────────────────────────────
# Helper: segment-level predictor
# ────────────────────────────────────────────────────────────
def _predict_segment(seg_audio, model, mean, std, sr):
    features = extract_mfcc_features(seg_audio, sr) # (T, 120)

    # Normalize features using the global mean and std
    # mean and std are (1, 1, 120) so they broadcast correctly
    normalized_features = (features - mean) / std

    # Pad/truncate the features to MAX_TIMESTEPS
    # pad_sequences expects a list of sequences
    padded_features = pad_sequences([normalized_features], maxlen=MAX_TIMESTEPS, dtype='float32',
                                    padding='post', truncating='post') # (1, MAX_TIMESTEPS, 120)

    # The model expects a batch of sequences, so padded_features is already in the correct shape
    probs = model.predict(padded_features, verbose=0)[0]
    return int(np.argmax(probs)), probs

def _sliding_labels(audio, model, mean, std, sr,
                    window_sec=0.5, hop_sec=0.1, smooth_k=5):
    win_samples = int(window_sec * sr)
    hop_samples = int(hop_sec    * sr)
    raw, times  = [], []
    pos = 0
    while pos + win_samples <= len(audio):
        seg   = audio[pos : pos + win_samples]
        label, _ = _predict_segment(seg, model, mean, std, sr)
        raw.append(label)
        times.append((pos + win_samples / 2) / sr)
        pos += hop_samples
    # Majority-vote smoothing
    half     = smooth_k // 2
    smoothed = []
    for i in range(len(raw)):
        w = raw[max(0, i-half) : i+half+1]
        smoothed.append(max(set(w), key=w.count))
    return smoothed, times

# ────────────────────────────────────────────────────────────
# Helper: clean one file
# ────────────────────────────────────────────────────────────
IDX_SPEECH = CLASS_TO_IDX["speech"]
MARGIN_SEC = 0.05   # 50 ms grace margin kept around speech

def _clean_file(input_path, output_path, sr=SAMPLE_RATE):
    audio         = load_any_audio(input_path, sr)   # ← handles WAV & MP3
    labels, times = _sliding_labels(audio, model, mean, std, sr)
    hop_samples   = int(0.1 * sr)
    win_samples   = int(0.5 * sr)

    speech_hops = [i for i, l in enumerate(labels) if l == IDX_SPEECH]

    if not speech_hops:
        print(" No speech detected — saving original unchanged. ")
        sf.write(output_path, audio, sr)
        return audio, audio, labels, times

    first_hop    = speech_hops[0]
    last_hop     = speech_hops[-1]
    start_sample = max(0,          first_hop * hop_samples - int(MARGIN_SEC * sr))
    end_sample   = min(len(audio), last_hop  * hop_samples + win_samples + int(MARGIN_SEC * sr))

    cleaned = audio[start_sample:end_sample]
    sf.write(output_path, cleaned, sr)   # always saves as WAV
    return audio, cleaned, labels, times

# ────────────────────────────────────────────────────────────
# Helper: colour-coded label timeline
# ────────────────────────────────────────────────────────────
LABEL_COLOURS = {
    CLASS_TO_IDX["silence"]:      "#4e8ef7",
    CLASS_TO_IDX["button_click"]: "#f76e4e",
    CLASS_TO_IDX["speech"]:       "#4ef7a0",
}

def _plot_timeline(ax, labels, times, hop_sec=0.1):
    for i, (label, t) in enumerate(zip(labels, times)):
        ax.axvspan(t - hop_sec/2, t + hop_sec/2,
                   color=LABEL_COLOURS[label], alpha=0.4, linewidth=0)
    from matplotlib.patches import Patch
    patches = [Patch(color=LABEL_COLOURS[CLASS_TO_IDX[c]], label=c)
               for c in CLASSES]
    ax.legend(handles=patches, loc="upper right", fontsize=8)

# ════════════════════════════════════════════════════════════
# MAIN — Upload → Clean → Display → Download
# ════════════════════════════════════════════════════════════

print(" Select one or more .wav or .mp3 files to upload …\n ")
uploaded = files.upload()   # ← opens file picker

if not uploaded:
    print("No files uploaded.")
else:
    skipped = []

    for filename, file_bytes in uploaded.items():

        # ── Check extension ──────────────────────────────────
        ext = Path(filename).suffix.lower()
        if ext not in SUPPORTED_EXTENSIONS:
            print(f" Skipping '{filename}' — unsupported format '{ext}'. "
                  f"Please upload .wav or .mp3 files only.")
            skipped.append(filename)
            continue

        # ── Save uploaded bytes ──────────────────────────────
        input_path  = os.path.join(UPLOAD_DIR, filename)
        stem        = Path(filename).stem
        output_name = f"{stem}_clean.wav"          # output is always WAV
        output_path = os.path.join(CLEAN_DIR, output_name)

        with open(input_path, "wb") as f:
            f.write(file_bytes)

        fmt_label = "MP3" if ext == ".mp3" else "WAV"
        print(f"\n Uploaded : {filename}  ({len(file_bytes)/1024:.1f} KB)  [{fmt_label}]")

        # ── Run cleaner ──────────────────────────────────────
        print("   Running LSTM cleaner …")
        original, cleaned, labels, times = _clean_file(input_path, output_path)

        dur_orig    = len(original) / SAMPLE_RATE
        dur_clean   = len(cleaned)  / SAMPLE_RATE
        dur_removed = dur_orig - dur_clean
        print(f"   Original  : {dur_orig:.2f}s")
        print(f"   Cleaned   : {dur_clean:.2f}s")
        print(f"   Removed   : {dur_removed:.2f}s of silence / button clicks")

        # ── Plot ─────────────────────────────────────────────
        fig = plt.figure(figsize=(15, 8))
        fig.suptitle(f"Audio Cleaner — {filename}  [{fmt_label}]",
                     fontsize=13, fontweight="bold")
        gs  = gridspec.GridSpec(3, 1, hspace=0.55)

        ax0 = fig.add_subplot(gs[0])
        librosa.display.waveshow(original, sr=SAMPLE_RATE, ax=ax0, color="#4e8ef7")
        ax0.set_title("Original Audio")
        ax0.set_xlabel("Time (s)")

        ax1 = fig.add_subplot(gs[1])
        librosa.display.waveshow(original, sr=SAMPLE_RATE, ax=ax1,
                                 color="grey", alpha=0.4)
        _plot_timeline(ax1, labels, times)
        ax1.set_title("Predicted Labels  (blue = silence | red = button click | green = speech)")
        ax1.set_xlabel("Time (s)")

        ax2 = fig.add_subplot(gs[2])
        librosa.display.waveshow(cleaned, sr=SAMPLE_RATE, ax=ax2, color="#4ef7a0")
        ax2.set_title(f"Cleaned Audio  ({dur_clean:.2f}s)")
        ax2.set_xlabel("Time (s)")

        plt.savefig(os.path.join(CLEAN_DIR, f"{stem}_comparison.png"),
                    dpi=150, bbox_inches="tight")
        plt.show()

        # ── Audio players ────────────────────────────────────
        print("\n▶  Original:")
        ipd.display(ipd.Audio(original, rate=SAMPLE_RATE))
        print("▶  Cleaned:")
        ipd.display(ipd.Audio(cleaned,  rate=SAMPLE_RATE))

        # ── Download ─────────────────────────────────────────
        print(f"\n⬇️  Downloading cleaned file: {output_name}")
        files.download(output_path)

    # ── Summary ──────────────────────────────────────────────
    processed = len(uploaded) - len(skipped)
    print(f"\n Done — {processed} file(s) cleaned and downloaded.", end="")
    if skipped:
        print(f"  {len(skipped)} skipped: {', '.join(skipped)}", end="")
    print()

# ============================================================
# CELL 19 — Upload, Clean & Download Audio (WAV + MP3)
#
# Run this cell AFTER training (or after Cell 18 if reloading
# a saved model).  It will:
#   1. Pop up a file picker — accepts .wav OR .mp3 files
#   2. Run the LSTM cleaner on each uploaded file
#   3. Show a before/after waveform + label timeline
#   4. Let you play both clips inside the notebook
#   5. Auto-download the cleaned file as a .wav to your computer
# ============================================================

import os
import numpy as np
import librosa
import librosa.display
import soundfile as sf
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
import IPython.display as ipd
from pathlib import Path
from google.colab import files
from tensorflow.keras.preprocessing.sequence import pad_sequences # Import pad_sequences

# ── Paths ────────────────────────────────────────────────────
UPLOAD_DIR = "/content/uploaded_audio"
CLEAN_DIR  = "/content/cleaned_audio"
os.makedirs(UPLOAD_DIR, exist_ok=True)
os.makedirs(CLEAN_DIR,  exist_ok=True)

# ── Supported formats ─────────────────────────────────────────
SUPPORTED_EXTENSIONS = {".wav", ".mp3"}

# ────────────────────────────────────────────────────────────
# Helper: load audio — works for both WAV and MP3
# librosa.load() handles MP3 decoding automatically via audioread
# ────────────────────────────────────────────────────────────
def load_any_audio(path, sr=SAMPLE_RATE):
    """Load WAV or MP3 and return a mono float32 numpy array."""
    y, _ = librosa.load(str(path), sr=sr, mono=True)
    return y

# ────────────────────────────────────────────────────────────
# Helper: segment-level predictor
# ────────────────────────────────────────────────────────────
def _predict_segment(seg_audio, model, mean, std, sr):
    features = extract_mfcc_features(seg_audio, sr) # (T, 120)

    # Normalize features using the global mean and std
    # mean and std are (1, 1, 120) so they broadcast correctly
    normalized_features = (features - mean) / std

    # Pad/truncate the features to MAX_TIMESTEPS
    # pad_sequences expects a list of sequences
    padded_features = pad_sequences([normalized_features], maxlen=MAX_TIMESTEPS, dtype='float32',
                                    padding='post', truncating='post') # (1, MAX_TIMESTEPS, 120)

    # The model expects a batch of sequences, so padded_features is already in the correct shape
    probs = model.predict(padded_features, verbose=0)[0]
    return int(np.argmax(probs)), probs

def _sliding_labels(audio, model, mean, std, sr,
                    window_sec=0.5, hop_sec=0.1, smooth_k=5):
    win_samples = int(window_sec * sr)
    hop_samples = int(hop_sec    * sr)
    raw, times  = [], []
    pos = 0
    while pos + win_samples <= len(audio):
        seg   = audio[pos : pos + win_samples]
        label, _ = _predict_segment(seg, model, mean, std, sr)
        raw.append(label)
        times.append((pos + win_samples / 2) / sr)
        pos += hop_samples
    # Majority-vote smoothing
    half     = smooth_k // 2
    smoothed = []
    for i in range(len(raw)):
        w = raw[max(0, i-half) : i+half+1]
        smoothed.append(max(set(w), key=w.count))
    return smoothed, times

# ────────────────────────────────────────────────────────────
# Helper: clean one file
# ────────────────────────────────────────────────────────────
IDX_SPEECH = CLASS_TO_IDX["speech"]
MARGIN_SEC = 0.05   # 50 ms grace margin kept around speech

def _clean_file(input_path, output_path, sr=SAMPLE_RATE):
    audio         = load_any_audio(input_path, sr)   # ← handles WAV & MP3
    labels, times = _sliding_labels(audio, model, mean, std, sr)
    hop_samples   = int(0.1 * sr)
    win_samples   = int(0.5 * sr)

    speech_hops = [i for i, l in enumerate(labels) if l == IDX_SPEECH]

    if not speech_hops:
        print(" No speech detected — saving original unchanged. ")
        sf.write(output_path, audio, sr)
        return audio, audio, labels, times

    first_hop    = speech_hops[0]
    last_hop     = speech_hops[-1]
    start_sample = max(0,          first_hop * hop_samples - int(MARGIN_SEC * sr))
    end_sample   = min(len(audio), last_hop  * hop_samples + win_samples + int(MARGIN_SEC * sr))

    cleaned = audio[start_sample:end_sample]
    sf.write(output_path, cleaned, sr)   # always saves as WAV
    return audio, cleaned, labels, times

# ────────────────────────────────────────────────────────────
# Helper: colour-coded label timeline
# ────────────────────────────────────────────────────────────
LABEL_COLOURS = {
    CLASS_TO_IDX["silence"]:      "#4e8ef7",
    CLASS_TO_IDX["button_click"]: "#f76e4e",
    CLASS_TO_IDX["speech"]:       "#4ef7a0",
}

def _plot_timeline(ax, labels, times, hop_sec=0.1):
    for i, (label, t) in enumerate(zip(labels, times)):
        ax.axvspan(t - hop_sec/2, t + hop_sec/2,
                   color=LABEL_COLOURS[label], alpha=0.4, linewidth=0)
    from matplotlib.patches import Patch
    patches = [Patch(color=LABEL_COLOURS[CLASS_TO_IDX[c]], label=c)
               for c in CLASSES]
    ax.legend(handles=patches, loc="upper right", fontsize=8)

# ════════════════════════════════════════════════════════════
# MAIN — Upload → Clean → Display → Download
# ════════════════════════════════════════════════════════════

print(" Select one or more .wav or .mp3 files to upload …\n ")
uploaded = files.upload()   # ← opens file picker

if not uploaded:
    print("No files uploaded.")
else:
    skipped = []

    for filename, file_bytes in uploaded.items():

        # ── Check extension ──────────────────────────────────
        ext = Path(filename).suffix.lower()
        if ext not in SUPPORTED_EXTENSIONS:
            print(f" Skipping '{filename}' — unsupported format '{ext}'. "
                  f"Please upload .wav or .mp3 files only.")
            skipped.append(filename)
            continue

        # ── Save uploaded bytes ──────────────────────────────
        input_path  = os.path.join(UPLOAD_DIR, filename)
        stem        = Path(filename).stem
        output_name = f"{stem}_clean.wav"          # output is always WAV
        output_path = os.path.join(CLEAN_DIR, output_name)

        with open(input_path, "wb") as f:
            f.write(file_bytes)

        fmt_label = "MP3" if ext == ".mp3" else "WAV"
        print(f"\n Uploaded : {filename}  ({len(file_bytes)/1024:.1f} KB)  [{fmt_label}]")

        # ── Run cleaner ──────────────────────────────────────
        print("   Running LSTM cleaner …")
        original, cleaned, labels, times = _clean_file(input_path, output_path)

        dur_orig    = len(original) / SAMPLE_RATE
        dur_clean   = len(cleaned)  / SAMPLE_RATE
        dur_removed = dur_orig - dur_clean
        print(f"   Original  : {dur_orig:.2f}s")
        print(f"   Cleaned   : {dur_clean:.2f}s")
        print(f"   Removed   : {dur_removed:.2f}s of silence / button clicks")

        # ── Plot ─────────────────────────────────────────────
        fig = plt.figure(figsize=(15, 8))
        fig.suptitle(f"Audio Cleaner — {filename}  [{fmt_label}]",
                     fontsize=13, fontweight="bold")
        gs  = gridspec.GridSpec(3, 1, hspace=0.55)

        ax0 = fig.add_subplot(gs[0])
        librosa.display.waveshow(original, sr=SAMPLE_RATE, ax=ax0, color="#4e8ef7")
        ax0.set_title("Original Audio")
        ax0.set_xlabel("Time (s)")

        ax1 = fig.add_subplot(gs[1])
        librosa.display.waveshow(original, sr=SAMPLE_RATE, ax=ax1,
                                 color="grey", alpha=0.4)
        _plot_timeline(ax1, labels, times)
        ax1.set_title("Predicted Labels  (blue = silence | red = button click | green = speech)")
        ax1.set_xlabel("Time (s)")

        ax2 = fig.add_subplot(gs[2])
        librosa.display.waveshow(cleaned, sr=SAMPLE_RATE, ax=ax2, color="#4ef7a0")
        ax2.set_title(f"Cleaned Audio  ({dur_clean:.2f}s)")
        ax2.set_xlabel("Time (s)")

        plt.savefig(os.path.join(CLEAN_DIR, f"{stem}_comparison.png"),
                    dpi=150, bbox_inches="tight")
        plt.show()

        # ── Audio players ────────────────────────────────────
        print("\n▶  Original:")
        ipd.display(ipd.Audio(original, rate=SAMPLE_RATE))
        print("▶  Cleaned:")
        ipd.display(ipd.Audio(cleaned,  rate=SAMPLE_RATE))

        # ── Download ─────────────────────────────────────────
        print(f"\n⬇️  Downloading cleaned file: {output_name}")
        files.download(output_path)

    # ── Summary ──────────────────────────────────────────────
    processed = len(uploaded) - len(skipped)
    print(f"\n  Done — {processed} file(s) cleaned and downloaded.", end="")
    if skipped:
        print(f"  {len(skipped)} skipped: {', '.join(skipped)}", end="")
    print()

# ============================================================
# CELL 19 — Upload, Clean & Download Audio (WAV + MP3)
#
# Run this cell AFTER training (or after Cell 18 if reloading
# a saved model).  It will:
#   1. Pop up a file picker — accepts .wav OR .mp3 files
#   2. Run the LSTM cleaner on each uploaded file
#   3. Show a before/after waveform + label timeline
#   4. Let you play both clips inside the notebook
#   5. Auto-download the cleaned file as a .wav to your computer
# ============================================================

import os
import numpy as np
import librosa
import librosa.display
import soundfile as sf
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
import IPython.display as ipd
from pathlib import Path
from google.colab import files
from tensorflow.keras.preprocessing.sequence import pad_sequences # Import pad_sequences

# ── Paths ────────────────────────────────────────────────────
UPLOAD_DIR = "/content/uploaded_audio"
CLEAN_DIR  = "/content/cleaned_audio"
os.makedirs(UPLOAD_DIR, exist_ok=True)
os.makedirs(CLEAN_DIR,  exist_ok=True)

# ── Supported formats ─────────────────────────────────────────
SUPPORTED_EXTENSIONS = {".wav", ".mp3"}

# ────────────────────────────────────────────────────────────
# Helper: load audio — works for both WAV and MP3
# librosa.load() handles MP3 decoding automatically via audioread
# ────────────────────────────────────────────────────────────
def load_any_audio(path, sr=SAMPLE_RATE):
    """Load WAV or MP3 and return a mono float32 numpy array."""
    y, _ = librosa.load(str(path), sr=sr, mono=True)
    return y

# ────────────────────────────────────────────────────────────
# Helper: segment-level predictor
# ────────────────────────────────────────────────────────────
def _predict_segment(seg_audio, model, mean, std, sr):
    features = extract_mfcc_features(seg_audio, sr) # (T, 120)

    # Normalize features using the global mean and std
    # mean and std are (1, 1, 120) so they broadcast correctly
    normalized_features = (features - mean) / std

    # Pad/truncate the features to MAX_TIMESTEPS
    # pad_sequences expects a list of sequences
    padded_features = pad_sequences([normalized_features], maxlen=MAX_TIMESTEPS, dtype='float32',
                                    padding='post', truncating='post') # (1, MAX_TIMESTEPS, 120)

    # The model expects a batch of sequences, so padded_features is already in the correct shape
    probs = model.predict(padded_features, verbose=0)[0]
    return int(np.argmax(probs)), probs

def _sliding_labels(audio, model, mean, std, sr,
                    window_sec=0.5, hop_sec=0.1, smooth_k=5):
    win_samples = int(window_sec * sr)
    hop_samples = int(hop_sec    * sr)
    raw, times  = [], []
    pos = 0
    while pos + win_samples <= len(audio):
        seg   = audio[pos : pos + win_samples]
        label, _ = _predict_segment(seg, model, mean, std, sr)
        raw.append(label)
        times.append((pos + win_samples / 2) / sr)
        pos += hop_samples
    # Majority-vote smoothing
    half     = smooth_k // 2
    smoothed = []
    for i in range(len(raw)):
        w = raw[max(0, i-half) : i+half+1]
        smoothed.append(max(set(w), key=w.count))
    return smoothed, times

# ────────────────────────────────────────────────────────────
# Helper: clean one file
# ────────────────────────────────────────────────────────────
IDX_SPEECH = CLASS_TO_IDX["speech"]
MARGIN_SEC = 0.05   # 50 ms grace margin kept around speech

def _clean_file(input_path, output_path, sr=SAMPLE_RATE):
    audio         = load_any_audio(input_path, sr)   # ← handles WAV & MP3
    labels, times = _sliding_labels(audio, model, mean, std, sr)
    hop_samples   = int(0.1 * sr)
    win_samples   = int(0.5 * sr)

    speech_hops = [i for i, l in enumerate(labels) if l == IDX_SPEECH]

    if not speech_hops:
        print(" No speech detected — saving original unchanged. ")
        sf.write(output_path, audio, sr)
        return audio, audio, labels, times

    first_hop    = speech_hops[0]
    last_hop     = speech_hops[-1]
    start_sample = max(0,          first_hop * hop_samples - int(MARGIN_SEC * sr))
    end_sample   = min(len(audio), last_hop  * hop_samples + win_samples + int(MARGIN_SEC * sr))

    cleaned = audio[start_sample:end_sample]
    sf.write(output_path, cleaned, sr)   # always saves as WAV
    return audio, cleaned, labels, times

# ────────────────────────────────────────────────────────────
# Helper: colour-coded label timeline
# ────────────────────────────────────────────────────────────
LABEL_COLOURS = {
    CLASS_TO_IDX["silence"]:      "#4e8ef7",
    CLASS_TO_IDX["button_click"]: "#f76e4e",
    CLASS_TO_IDX["speech"]:       "#4ef7a0",
}

def _plot_timeline(ax, labels, times, hop_sec=0.1):
    for i, (label, t) in enumerate(zip(labels, times)):
        ax.axvspan(t - hop_sec/2, t + hop_sec/2,
                   color=LABEL_COLOURS[label], alpha=0.4, linewidth=0)
    from matplotlib.patches import Patch
    patches = [Patch(color=LABEL_COLOURS[CLASS_TO_IDX[c]], label=c)
               for c in CLASSES]
    ax.legend(handles=patches, loc="upper right", fontsize=8)

# ════════════════════════════════════════════════════════════
# MAIN — Upload → Clean → Display → Download
# ════════════════════════════════════════════════════════════

print(" Select one or more .wav or .mp3 files to upload …\n")
uploaded = files.upload()   # ← opens file picker

if not uploaded:
    print("No files uploaded.")
else:
    skipped = []

    for filename, file_bytes in uploaded.items():

        # ── Check extension ──────────────────────────────────
        ext = Path(filename).suffix.lower()
        if ext not in SUPPORTED_EXTENSIONS:
            print(f" Skipping '{filename}' — unsupported format '{ext}'. "
                  f"Please upload .wav or .mp3 files only.")
            skipped.append(filename)
            continue

        # ── Save uploaded bytes ──────────────────────────────
        input_path  = os.path.join(UPLOAD_DIR, filename)
        stem        = Path(filename).stem
        output_name = f"{stem}_clean.wav"          # output is always WAV
        output_path = os.path.join(CLEAN_DIR, output_name)

        with open(input_path, "wb") as f:
            f.write(file_bytes)

        fmt_label = "MP3" if ext == ".mp3" else "WAV"
        print(f"\n Uploaded : {filename}  ({len(file_bytes)/1024:.1f} KB)  [{fmt_label}]")

        # ── Run cleaner ──────────────────────────────────────
        print("   Running LSTM cleaner …")
        original, cleaned, labels, times = _clean_file(input_path, output_path)

        dur_orig    = len(original) / SAMPLE_RATE
        dur_clean   = len(cleaned)  / SAMPLE_RATE
        dur_removed = dur_orig - dur_clean
        print(f"   Original  : {dur_orig:.2f}s")
        print(f"   Cleaned   : {dur_clean:.2f}s")
        print(f"   Removed   : {dur_removed:.2f}s of silence / button clicks")

        # ── Plot ─────────────────────────────────────────────
        fig = plt.figure(figsize=(15, 8))
        fig.suptitle(f"Audio Cleaner — {filename}  [{fmt_label}]",
                     fontsize=13, fontweight="bold")
        gs  = gridspec.GridSpec(3, 1, hspace=0.55)

        ax0 = fig.add_subplot(gs[0])
        librosa.display.waveshow(original, sr=SAMPLE_RATE, ax=ax0, color="#4e8ef7")
        ax0.set_title("Original Audio")
        ax0.set_xlabel("Time (s)")

        ax1 = fig.add_subplot(gs[1])
        librosa.display.waveshow(original, sr=SAMPLE_RATE, ax=ax1,
                                 color="grey", alpha=0.4)
        _plot_timeline(ax1, labels, times)
        ax1.set_title("Predicted Labels  (blue = silence | red = button click | green = speech)")
        ax1.set_xlabel("Time (s)")

        ax2 = fig.add_subplot(gs[2])
        librosa.display.waveshow(cleaned, sr=SAMPLE_RATE, ax=ax2, color="#4ef7a0")
        ax2.set_title(f"Cleaned Audio  ({dur_clean:.2f}s)")
        ax2.set_xlabel("Time (s)")

        plt.savefig(os.path.join(CLEAN_DIR, f"{stem}_comparison.png"),
                    dpi=150, bbox_inches="tight")
        plt.show()

        # ── Audio players ────────────────────────────────────
        print("\n▶  Original:")
        ipd.display(ipd.Audio(original, rate=SAMPLE_RATE))
        print("▶  Cleaned:")
        ipd.display(ipd.Audio(cleaned,  rate=SAMPLE_RATE))

        # ── Download ─────────────────────────────────────────
        print(f"\n⬇️  Downloading cleaned file: {output_name}")
        files.download(output_path)

    # ── Summary ──────────────────────────────────────────────
    processed = len(uploaded) - len(skipped)
    print(f"\n Done — {processed} file(s) cleaned and downloaded.", end="")
    if skipped:
        print(f"  {len(skipped)} skipped: {', '.join(skipped)}", end="")
    print()

# ============================================================
# CELL 19 — Upload, Clean & Download Audio (WAV + MP3)
#
# Run this cell AFTER training (or after Cell 18 if reloading
# a saved model).  It will:
#   1. Pop up a file picker — accepts .wav OR .mp3 files
#   2. Run the LSTM cleaner on each uploaded file
#   3. Show a before/after waveform + label timeline
#   4. Let you play both clips inside the notebook
#   5. Auto-download the cleaned file as a .wav to your computer
# ============================================================

import os
import numpy as np
import librosa
import librosa.display
import soundfile as sf
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
import IPython.display as ipd
from pathlib import Path
from google.colab import files
from tensorflow.keras.preprocessing.sequence import pad_sequences # Import pad_sequences

# ── Paths ────────────────────────────────────────────────────
UPLOAD_DIR = "/content/uploaded_audio"
CLEAN_DIR  = "/content/cleaned_audio"
os.makedirs(UPLOAD_DIR, exist_ok=True)
os.makedirs(CLEAN_DIR,  exist_ok=True)

# ── Supported formats ─────────────────────────────────────────
SUPPORTED_EXTENSIONS = {".wav", ".mp3"}

# ────────────────────────────────────────────────────────────
# Helper: load audio — works for both WAV and MP3
# librosa.load() handles MP3 decoding automatically via audioread
# ────────────────────────────────────────────────────────────
def load_any_audio(path, sr=SAMPLE_RATE):
    """Load WAV or MP3 and return a mono float32 numpy array."""
    y, _ = librosa.load(str(path), sr=sr, mono=True)
    return y

# ────────────────────────────────────────────────────────────
# Helper: segment-level predictor
# ────────────────────────────────────────────────────────────
def _predict_segment(seg_audio, model, mean, std, sr):
    features = extract_mfcc_features(seg_audio, sr) # (T, 120)

    # Normalize features using the global mean and std
    # mean and std are (1, 1, 120) so they broadcast correctly
    normalized_features = (features - mean) / std

    # Pad/truncate the features to MAX_TIMESTEPS
    # pad_sequences expects a list of sequences
    padded_features = pad_sequences([normalized_features], maxlen=MAX_TIMESTEPS, dtype='float32',
                                    padding='post', truncating='post') # (1, MAX_TIMESTEPS, 120)

    # The model expects a batch of sequences, so padded_features is already in the correct shape
    probs = model.predict(padded_features, verbose=0)[0]
    return int(np.argmax(probs)), probs

def _sliding_labels(audio, model, mean, std, sr,
                    window_sec=0.5, hop_sec=0.1, smooth_k=5):
    win_samples = int(window_sec * sr)
    hop_samples = int(hop_sec    * sr)
    raw, times  = [], []
    pos = 0
    while pos + win_samples <= len(audio):
        seg   = audio[pos : pos + win_samples]
        label, _ = _predict_segment(seg, model, mean, std, sr)
        raw.append(label)
        times.append((pos + win_samples / 2) / sr)
        pos += hop_samples
    # Majority-vote smoothing
    half     = smooth_k // 2
    smoothed = []
    for i in range(len(raw)):
        w = raw[max(0, i-half) : i+half+1]
        smoothed.append(max(set(w), key=w.count))
    return smoothed, times

# ────────────────────────────────────────────────────────────
# Helper: clean one file
# ────────────────────────────────────────────────────────────
IDX_SPEECH = CLASS_TO_IDX["speech"]
MARGIN_SEC = 0.05   # 50 ms grace margin kept around speech

def _clean_file(input_path, output_path, sr=SAMPLE_RATE):
    audio         = load_any_audio(input_path, sr)   # ← handles WAV & MP3
    labels, times = _sliding_labels(audio, model, mean, std, sr)
    hop_samples   = int(0.1 * sr)
    win_samples   = int(0.5 * sr)

    speech_hops = [i for i, l in enumerate(labels) if l == IDX_SPEECH]

    if not speech_hops:
        print(" No speech detected — saving original unchanged. ")
        sf.write(output_path, audio, sr)
        return audio, audio, labels, times

    first_hop    = speech_hops[0]
    last_hop     = speech_hops[-1]
    start_sample = max(0,          first_hop * hop_samples - int(MARGIN_SEC * sr))
    end_sample   = min(len(audio), last_hop  * hop_samples + win_samples + int(MARGIN_SEC * sr))

    cleaned = audio[start_sample:end_sample]
    sf.write(output_path, cleaned, sr)   # always saves as WAV
    return audio, cleaned, labels, times

# ────────────────────────────────────────────────────────────
# Helper: colour-coded label timeline
# ────────────────────────────────────────────────────────────
LABEL_COLOURS = {
    CLASS_TO_IDX["silence"]:      "#4e8ef7",
    CLASS_TO_IDX["button_click"]: "#f76e4e",
    CLASS_TO_IDX["speech"]:       "#4ef7a0",
}

def _plot_timeline(ax, labels, times, hop_sec=0.1):
    for i, (label, t) in enumerate(zip(labels, times)):
        ax.axvspan(t - hop_sec/2, t + hop_sec/2,
                   color=LABEL_COLOURS[label], alpha=0.4, linewidth=0)
    from matplotlib.patches import Patch
    patches = [Patch(color=LABEL_COLOURS[CLASS_TO_IDX[c]], label=c)
               for c in CLASSES]
    ax.legend(handles=patches, loc="upper right", fontsize=8)

# ════════════════════════════════════════════════════════════
# MAIN — Upload → Clean → Display → Download
# ════════════════════════════════════════════════════════════

print(" Select one or more .wav or .mp3 files to upload …\n ")
uploaded = files.upload()   # ← opens file picker

if not uploaded:
    print("No files uploaded.")
else:
    skipped = []

    for filename, file_bytes in uploaded.items():

        # ── Check extension ──────────────────────────────────
        ext = Path(filename).suffix.lower()
        if ext not in SUPPORTED_EXTENSIONS:
            print(f" Skipping '{filename}' — unsupported format '{ext}'. "
                  f"Please upload .wav or .mp3 files only.")
            skipped.append(filename)
            continue

        # ── Save uploaded bytes ──────────────────────────────
        input_path  = os.path.join(UPLOAD_DIR, filename)
        stem        = Path(filename).stem
        output_name = f"{stem}_clean.wav"          # output is always WAV
        output_path = os.path.join(CLEAN_DIR, output_name)

        with open(input_path, "wb") as f:
            f.write(file_bytes)

        fmt_label = "MP3" if ext == ".mp3" else "WAV"
        print(f"\n Uploaded : {filename}  ({len(file_bytes)/1024:.1f} KB)  [{fmt_label}]")

        # ── Run cleaner ──────────────────────────────────────
        print("   Running LSTM cleaner …")
        original, cleaned, labels, times = _clean_file(input_path, output_path)

        dur_orig    = len(original) / SAMPLE_RATE
        dur_clean   = len(cleaned)  / SAMPLE_RATE
        dur_removed = dur_orig - dur_clean
        print(f"   Original  : {dur_orig:.2f}s")
        print(f"   Cleaned   : {dur_clean:.2f}s")
        print(f"   Removed   : {dur_removed:.2f}s of silence / button clicks")

        # ── Plot ─────────────────────────────────────────────
        fig = plt.figure(figsize=(15, 8))
        fig.suptitle(f"Audio Cleaner — {filename}  [{fmt_label}]",
                     fontsize=13, fontweight="bold")
        gs  = gridspec.GridSpec(3, 1, hspace=0.55)

        ax0 = fig.add_subplot(gs[0])
        librosa.display.waveshow(original, sr=SAMPLE_RATE, ax=ax0, color="#4e8ef7")
        ax0.set_title("Original Audio")
        ax0.set_xlabel("Time (s)")

        ax1 = fig.add_subplot(gs[1])
        librosa.display.waveshow(original, sr=SAMPLE_RATE, ax=ax1,
                                 color="grey", alpha=0.4)
        _plot_timeline(ax1, labels, times)
        ax1.set_title("Predicted Labels  (blue = silence | red = button click | green = speech)")
        ax1.set_xlabel("Time (s)")

        ax2 = fig.add_subplot(gs[2])
        librosa.display.waveshow(cleaned, sr=SAMPLE_RATE, ax=ax2, color="#4ef7a0")
        ax2.set_title(f"Cleaned Audio  ({dur_clean:.2f}s)")
        ax2.set_xlabel("Time (s)")

        plt.savefig(os.path.join(CLEAN_DIR, f"{stem}_comparison.png"),
                    dpi=150, bbox_inches="tight")
        plt.show()

        # ── Audio players ────────────────────────────────────
        print("\n▶  Original:")
        ipd.display(ipd.Audio(original, rate=SAMPLE_RATE))
        print("▶  Cleaned:")
        ipd.display(ipd.Audio(cleaned,  rate=SAMPLE_RATE))

        # ── Download ─────────────────────────────────────────
        print(f"\n⬇️  Downloading cleaned file: {output_name}")
        files.download(output_path)

    # ── Summary ──────────────────────────────────────────────
    processed = len(uploaded) - len(skipped)
    print(f"\n Done — {processed} file(s) cleaned and downloaded.", end="")
    if skipped:
        print(f"  {len(skipped)} skipped: {', '.join(skipped)}", end="")
    print()
