# -*- coding: utf-8 -*-
"""Audio splitter 3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iLFWVmoxeUYeGS8BoUY2jTsFzQEMZnGW
"""

# -*- coding: utf-8 -*-
"""VAD Audio Splitter — Energy-Based Split Point Search
Colab notebook: VAD-based audio splitting with original-audio playback.

Changes vs audio_splitter_2.py:
  1. Hard-split in Pass 2 (merge_into_max_segments) is replaced with
     find_energy_split_point() — scans backwards from the 30 s mark through
     a configurable search window (default 5 s) to find the quietest 100 ms
     chunk, which is almost always a word/sentence boundary.
     Falls back to a hard cut ONLY if no quiet region exists at all, but logs
     a clear warning so you know exactly where it happened.
  2. Duplicate Cell 9 removed.
  3. All other prior fixes retained (original-audio preview, short-circuit
     path, temp-file cleanup, orig_sr print fix).
"""

# ── Cell 1 — Install dependencies
import subprocess, sys

packages = [
    "torch", "torchaudio", "pydub",
    "soundfile", "numpy", "ipywidgets", "IPython",
]
for pkg in packages:
    subprocess.check_call([sys.executable, "-m", "pip", "install", "-q", pkg])

# silero-vad is fetched from torch hub — no separate pip install needed
print("✅ All libraries installed successfully.")

# ── Cell 2 — Imports and global configuration
import os, torch, torchaudio, soundfile as sf
import numpy as np
from pydub import AudioSegment
from IPython.display import display, Audio, clear_output, HTML
import warnings; warnings.filterwarnings('ignore')

# ── Global Configuration
MAX_SEGMENT_DURATION_S  = 30     # soft ceiling — energy search tries to honour this
MIN_SEGMENT_DURATION_S  = 1      # discard VAD chunks shorter than this
VAD_THRESHOLD           = 0.5    # Silero speech probability threshold (0–1)
SAMPLING_RATE           = 16000  # VAD model requires 16 kHz
OUTPUT_DIR              = "split_output"

# Energy-search parameters (tune these if needed):
SEARCH_WINDOW_S         = 5.0    # how far back from the 30 s mark to scan (seconds)
                                  # reduce to 2.0–3.0 for stricter timing
QUIET_CHUNK_MS          = 100    # size of each energy probe (milliseconds)

os.makedirs(OUTPUT_DIR, exist_ok=True)
print(
    f"✅ Config ready | max={MAX_SEGMENT_DURATION_S}s | VAD={VAD_THRESHOLD} "
    f"| search_window={SEARCH_WINDOW_S}s | out='{OUTPUT_DIR}/'"
)

# ── Cell 3 — Load Silero VAD
print("Loading Silero VAD model...")

vad_model, vad_utils = torch.hub.load(
    repo_or_dir='snakers4/silero-vad',
    model='silero_vad',
    force_reload=False,
    onnx=False,
    verbose=False,
)

(get_speech_timestamps, _, read_audio,
 VADIterator, collect_chunks) = vad_utils

vad_model.eval()
print("✅ Silero VAD model loaded and ready.")

# ── Cell 4 — Audio loading and preprocessing helper
def load_and_preprocess_audio(file_path: str):
    """Load any supported audio file and return a 16 kHz mono tensor."""
    ext = os.path.splitext(file_path)[1].lower()

    if ext not in ('.wav', '.flac'):
        # pydub handles mp3 / m4a / ogg etc.
        audio_seg = AudioSegment.from_file(file_path)
        audio_seg = audio_seg.set_channels(1).set_frame_rate(SAMPLING_RATE)
        samples   = np.array(audio_seg.get_array_of_samples(), dtype=np.float32)
        samples  /= 2**15                           # normalise to [-1, 1]
        waveform_16k = torch.from_numpy(samples)
        orig_sr      = SAMPLING_RATE                # already resampled by pydub
    else:
        waveform, orig_sr = torchaudio.load(file_path)
        if waveform.shape[0] > 1:                   # stereo → mono
            waveform = waveform.mean(dim=0, keepdim=True)
        if orig_sr != SAMPLING_RATE:
            waveform = torchaudio.transforms.Resample(orig_sr, SAMPLING_RATE)(waveform)
        waveform_16k = waveform.squeeze()

    duration_s = len(waveform_16k) / SAMPLING_RATE
    return waveform_16k, orig_sr, duration_s

print("✅ Preprocessing helper defined.")

# ── Cell 5 — VAD speech-boundary detection
def detect_speech_segments(waveform_16k: torch.Tensor):
    """Run Silero VAD and return raw speech timestamp dicts."""
    timestamps = get_speech_timestamps(
        waveform_16k,
        vad_model,
        sampling_rate=SAMPLING_RATE,
        threshold=VAD_THRESHOLD,
        min_silence_duration_ms=300,
        min_speech_duration_ms=int(MIN_SEGMENT_DURATION_S * 1000),
        return_seconds=False,
    )
    print(f"   VAD found {len(timestamps)} raw speech region(s).")
    return timestamps

print("✅ VAD detection function defined.")

# ── Cell 6 — Energy-based split point search ──────────────────────────────────
def find_energy_split_point(
    waveform_16k: torch.Tensor,
    ideal_end_sample: int,
) -> int:
    """
    Scan backwards from `ideal_end_sample` through SEARCH_WINDOW_S of audio
    and return the sample index of the quietest QUIET_CHUNK_MS window.

    This is almost always a word or sentence boundary.

    If the entire search window is above the noise floor (extremely dense
    speech with no pauses), returns None so the caller can fall back to the
    hard cut and log a warning.

    Parameters
    ----------
    waveform_16k      : full audio tensor (1-D, float32, 16 kHz)
    ideal_end_sample  : where the hard cut *would* have been (= 30 s mark)

    Returns
    -------
    int | None  — best cut sample, or None if no quiet region found
    """
    chunk_samples  = int(QUIET_CHUNK_MS / 1000 * SAMPLING_RATE)   # e.g. 1600
    window_samples = int(SEARCH_WINDOW_S * SAMPLING_RATE)         # e.g. 80 000

    # Search range: [search_start … ideal_end_sample]
    search_start = max(0, ideal_end_sample - window_samples)
    audio_region = waveform_16k[search_start:ideal_end_sample].numpy()

    if len(audio_region) < chunk_samples:
        return None   # not enough audio to probe

    # Slide a QUIET_CHUNK_MS window and record RMS energy at each position
    best_rms       = float('inf')
    best_cut       = None
    step           = chunk_samples // 2        # 50 % overlap for smoother search

    for offset in range(0, len(audio_region) - chunk_samples + 1, step):
        chunk = audio_region[offset : offset + chunk_samples]
        rms   = float(np.sqrt(np.mean(chunk ** 2)))
        if rms < best_rms:
            best_rms = rms
            # Cut at the *start* of the quietest window (natural pause onset)
            best_cut = search_start + offset

    return best_cut   # may still be None if the loop never ran

print("✅ Energy-based split point search defined.")

# ── Cell 7 — Merge + energy-search split to respect the 30 s ceiling ──────────
def merge_into_max_segments(
    timestamps,
    total_samples: int,
    waveform_16k: torch.Tensor,
):
    """
    Merge consecutive VAD chunks into segments ≤ MAX_SEGMENT_DURATION_S.

    Two-pass approach:
      Pass 1 — greedily merge at VAD-detected silence boundaries.
      Pass 2 — any segment still > max (dense speech with no internal silence)
               is split using find_energy_split_point() instead of a blind
               sample-count cut.
               Falls back to hard cut ONLY when no quiet region is found, and
               logs a warning with the exact timestamp.

    Parameters
    ----------
    timestamps    : list of {'start': int, 'end': int} from Silero VAD
    total_samples : total length of waveform_16k in samples
    waveform_16k  : full audio tensor (needed for energy search in Pass 2)
    """
    max_samples = MAX_SEGMENT_DURATION_S * SAMPLING_RATE
    segments    = []

    if not timestamps:
        print("   ⚠️  No speech detected. Returning full audio as one segment.")
        return [(0, total_samples)]

    # ── Pass 1: merge at VAD silence boundaries ───────────────────────────────
    seg_start = timestamps[0]['start']
    seg_end   = timestamps[0]['end']

    for ts in timestamps[1:]:
        if (ts['end'] - seg_start) <= max_samples:
            seg_end = ts['end']                         # still fits — extend
        else:
            segments.append((seg_start, seg_end))       # close current segment
            seg_start = ts['start']
            seg_end   = ts['end']

    segments.append((seg_start, seg_end))               # flush the tail

    # ── Pass 2: energy-based split for anything still over the limit ──────────
    final_segments  = []
    hard_cut_count  = 0

    for (start, end) in segments:
        while (end - start) > max_samples:
            ideal_cut = start + int(max_samples)        # where the hard cut would be

            cut = find_energy_split_point(waveform_16k, ideal_cut)

            if cut is not None and cut > start:
                # ✅ Found a natural quiet boundary — use it
                final_segments.append((start, cut))
                start = cut
            else:
                # ⚠️ No quiet region found — fall back to hard cut and warn
                hard_cut_count += 1
                cut_time_s = ideal_cut / SAMPLING_RATE
                print(
                    f"   ⚠️  WARNING: no quiet region found near "
                    f"{cut_time_s:.2f} s — hard cut applied at that point. "
                    f"Consider reducing SEARCH_WINDOW_S or checking the audio "
                    f"for unusually dense speech."
                )
                final_segments.append((start, ideal_cut))
                start = ideal_cut

        if end > start:                                 # keep non-empty remainder
            final_segments.append((start, end))

    summary = (
        f"   Merged into {len(final_segments)} output segment(s) "
        f"(Pass-1 VAD boundaries: {len(segments)}"
    )
    if hard_cut_count:
        summary += f", energy splits used, {hard_cut_count} hard-cut fallback(s)"
    else:
        summary += ", all oversized chunks split at natural boundaries"
    summary += ")."
    print(summary)

    return final_segments

print("✅ Segment merging function defined.")

# ── Cell 8 — Save segments to disk as 16 kHz mono WAV files ──────────────────
def save_segments(waveform_16k: torch.Tensor, segments, base_name: str):
    """Slice the waveform at computed boundaries and write WAV files."""
    saved_paths   = []
    total_samples = len(waveform_16k)

    for i, (start, end) in enumerate(segments):
        start    = max(0, int(start))
        end      = min(int(end), total_samples)
        chunk    = waveform_16k[start:end].numpy()
        duration = (end - start) / SAMPLING_RATE
        out_path = os.path.join(OUTPUT_DIR, f"{base_name}_segment_{i+1:03d}.wav")
        sf.write(out_path, chunk, SAMPLING_RATE, subtype='PCM_16')
        saved_paths.append(out_path)
        print(f"   Saved segment {i+1:3d} | {duration:6.2f} s → {out_path}")

    return saved_paths

print("✅ Segment saving function defined.")

# ── Cell 9 — Master pipeline function ─────────────────────────────────────────
def split_audio(file_path: str):
    """
    Full pipeline: load → preprocess → VAD → merge+energy-split → save.
    Returns a list of saved segment file paths.
    """
    print(f"\n{'='*55}\n Processing: {os.path.basename(file_path)}\n{'='*55}")

    print("[1/4] Loading and preprocessing...")
    waveform_16k, orig_sr, duration_s = load_and_preprocess_audio(file_path)
    print(f"       Duration   : {duration_s:.2f} s")
    print(f"       Original SR: {orig_sr} Hz")

    # Short-circuit: already within the limit
    if duration_s <= MAX_SEGMENT_DURATION_S:
        print(f"   ℹ️  Already within {MAX_SEGMENT_DURATION_S} s — saving as-is.")
        base = os.path.splitext(os.path.basename(file_path))[0]
        out  = os.path.join(OUTPUT_DIR, f"{base}_segment_001.wav")
        sf.write(out, waveform_16k.numpy(), SAMPLING_RATE, subtype='PCM_16')
        return [out]

    print("[2/4] Running VAD...")
    timestamps = detect_speech_segments(waveform_16k)

    print("[3/4] Merging into output segments (energy-based split)...")
    segments = merge_into_max_segments(timestamps, len(waveform_16k), waveform_16k)

    print("[4/4] Saving segments...")
    base_name = os.path.splitext(os.path.basename(file_path))[0]
    saved = save_segments(waveform_16k, segments, base_name)

    print(f"\n✅ Done — {len(saved)} segment(s) written to '{OUTPUT_DIR}/'")
    return saved

print("✅ split_audio() pipeline ready.")

# ── Cell 10 — Interactive UI: upload → preview original → split → listen ──────
import ipywidgets as widgets
import tempfile

uploader     = widgets.FileUpload(
    accept='.wav,.mp3,.flac,.ogg,.m4a',
    multiple=False,
    description='Upload Audio',
    layout=widgets.Layout(width='300px'),
)
run_btn      = widgets.Button(description='✂️  Split Audio', button_style='success')
original_out = widgets.Output()   # shows the uploaded file's player immediately
out_area     = widgets.Output()   # shows split segments after the button is clicked

# ── Show original audio as soon as a file is selected ─────────────────────────
def on_upload_change(change):
    with original_out:
        clear_output(wait=True)
        if not uploader.value:
            return

        uploaded  = list(uploader.value.values())[0]
        fname     = list(uploader.value.keys())[0]
        ext       = os.path.splitext(fname)[1].lower()
        raw_bytes = bytes(uploaded['content'])

        # Write to a temp file so soundfile can decode any format
        tmp = tempfile.NamedTemporaryFile(suffix=ext, delete=False)
        tmp.write(raw_bytes)
        tmp.flush()
        tmp_path = tmp.name
        tmp.close()

        try:
            data, sr = sf.read(tmp_path)
            dur = len(data) / sr
            display(HTML(
                f"<b>📂 Original:</b> {fname} &nbsp;|&nbsp; "
                f"{dur:.2f} s &nbsp;|&nbsp; {sr} Hz"
            ))
            display(Audio(data=data, rate=sr, autoplay=False))
        except Exception as e:
            print(f"⚠️  Could not preview original file: {e}")
        finally:
            os.unlink(tmp_path)

uploader.observe(on_upload_change, names='value')

# ── Split and display segments when the button is clicked ─────────────────────
def on_split_clicked(_):
    with out_area:
        clear_output(wait=True)
        if not uploader.value:
            print("⚠️  Please upload an audio file first.")
            return

        uploaded  = list(uploader.value.values())[0]
        fname     = list(uploader.value.keys())[0]
        ext       = os.path.splitext(fname)[1]
        raw_bytes = bytes(uploaded['content'])

        # Write to a temp file for the pipeline
        tmp = tempfile.NamedTemporaryFile(suffix=ext, delete=False)
        tmp.write(raw_bytes)
        tmp.flush()
        tmp_path = tmp.name
        tmp.close()

        try:
            saved = split_audio(tmp_path)
        except Exception as e:
            print(f"❌ Error during split: {e}")
            return
        finally:
            os.unlink(tmp_path)   # safe to clean up — split_audio saves its own WAVs

        print("\n── 🔊 Segments ──────────────────────────────────────")
        for i, seg_path in enumerate(saved):
            data, sr = sf.read(seg_path)
            dur      = len(data) / sr
            display(HTML(
                f"<b>Segment {i+1}</b> &nbsp;|&nbsp; "
                f"{dur:.2f} s &nbsp;|&nbsp; {os.path.basename(seg_path)}"
            ))
            display(Audio(data=data, rate=sr, autoplay=False))

run_btn.on_click(on_split_clicked)

display(widgets.VBox([
    widgets.HTML(
        "<h3>🎙️ VAD Audio Splitter</h3>"
        "<p>1. Upload → 2. Listen to original → 3. Click Split → 4. Listen to segments</p>"
    ),
    uploader,
    original_out,                           # ← original file player (appears on upload)
    widgets.HTML("<hr style='margin:8px 0'>"),
    run_btn,
    out_area,                               # ← split segments (appear after clicking Split)
]))

# ── Cell 10 — Interactive UI: upload → preview original → split → listen ──────
import ipywidgets as widgets
import tempfile

uploader     = widgets.FileUpload(
    accept='.wav,.mp3,.flac,.ogg,.m4a',
    multiple=False,
    description='Upload Audio',
    layout=widgets.Layout(width='300px'),
)
run_btn      = widgets.Button(description='✂️  Split Audio', button_style='success')
original_out = widgets.Output()   # shows the uploaded file's player immediately
out_area     = widgets.Output()   # shows split segments after the button is clicked

# ── Show original audio as soon as a file is selected ─────────────────────────
def on_upload_change(change):
    with original_out:
        clear_output(wait=True)
        if not uploader.value:
            return

        uploaded  = list(uploader.value.values())[0]
        fname     = list(uploader.value.keys())[0]
        ext       = os.path.splitext(fname)[1].lower()
        raw_bytes = bytes(uploaded['content'])

        # Write to a temp file so soundfile can decode any format
        tmp = tempfile.NamedTemporaryFile(suffix=ext, delete=False)
        tmp.write(raw_bytes)
        tmp.flush()
        tmp_path = tmp.name
        tmp.close()

        try:
            data, sr = sf.read(tmp_path)
            dur = len(data) / sr
            display(HTML(
                f"<b>📂 Original:</b> {fname} &nbsp;|&nbsp; "
                f"{dur:.2f} s &nbsp;|&nbsp; {sr} Hz"
            ))
            display(Audio(data=data, rate=sr, autoplay=False))
        except Exception as e:
            print(f"⚠️  Could not preview original file: {e}")
        finally:
            os.unlink(tmp_path)

uploader.observe(on_upload_change, names='value')

# ── Split and display segments when the button is clicked ─────────────────────
def on_split_clicked(_):
    with out_area:
        clear_output(wait=True)
        if not uploader.value:
            print("⚠️  Please upload an audio file first.")
            return

        uploaded  = list(uploader.value.values())[0]
        fname     = list(uploader.value.keys())[0]
        ext       = os.path.splitext(fname)[1]
        raw_bytes = bytes(uploaded['content'])

        # Write to a temp file for the pipeline
        tmp = tempfile.NamedTemporaryFile(suffix=ext, delete=False)
        tmp.write(raw_bytes)
        tmp.flush()
        tmp_path = tmp.name
        tmp.close()

        try:
            saved = split_audio(tmp_path)
        except Exception as e:
            print(f"❌ Error during split: {e}")
            return
        finally:
            os.unlink(tmp_path)   # safe to clean up — split_audio saves its own WAVs

        print("\n── 🔊 Segments ──────────────────────────────────────")
        for i, seg_path in enumerate(saved):
            data, sr = sf.read(seg_path)
            dur      = len(data) / sr
            display(HTML(
                f"<b>Segment {i+1}</b> &nbsp;|&nbsp; "
                f"{dur:.2f} s &nbsp;|&nbsp; {os.path.basename(seg_path)}"
            ))
            display(Audio(data=data, rate=sr, autoplay=False))

run_btn.on_click(on_split_clicked)

display(widgets.VBox([
    widgets.HTML(
        "<h3>🎙️ VAD Audio Splitter</h3>"
        "<p>1. Upload → 2. Listen to original → 3. Click Split → 4. Listen to segments</p>"
    ),
    uploader,
    original_out,                           # ← original file player (appears on upload)
    widgets.HTML("<hr style='margin:8px 0'>"),
    run_btn,
    out_area,                               # ← split segments (appear after clicking Split)
]))

# ── Cell 10 — Interactive UI: upload → preview original → split → listen ──────
import ipywidgets as widgets
import tempfile

uploader     = widgets.FileUpload(
    accept='.wav,.mp3,.flac,.ogg,.m4a',
    multiple=False,
    description='Upload Audio',
    layout=widgets.Layout(width='300px'),
)
run_btn      = widgets.Button(description='✂️  Split Audio', button_style='success')
original_out = widgets.Output()   # shows the uploaded file's player immediately
out_area     = widgets.Output()   # shows split segments after the button is clicked

# ── Show original audio as soon as a file is selected ─────────────────────────
def on_upload_change(change):
    with original_out:
        clear_output(wait=True)
        if not uploader.value:
            return

        uploaded  = list(uploader.value.values())[0]
        fname     = list(uploader.value.keys())[0]
        ext       = os.path.splitext(fname)[1].lower()
        raw_bytes = bytes(uploaded['content'])

        # Write to a temp file so soundfile can decode any format
        tmp = tempfile.NamedTemporaryFile(suffix=ext, delete=False)
        tmp.write(raw_bytes)
        tmp.flush()
        tmp_path = tmp.name
        tmp.close()

        try:
            data, sr = sf.read(tmp_path)
            dur = len(data) / sr
            display(HTML(
                f"<b>📂 Original:</b> {fname} &nbsp;|&nbsp; "
                f"{dur:.2f} s &nbsp;|&nbsp; {sr} Hz"
            ))
            display(Audio(data=data, rate=sr, autoplay=False))
        except Exception as e:
            print(f"⚠️  Could not preview original file: {e}")
        finally:
            os.unlink(tmp_path)

uploader.observe(on_upload_change, names='value')

# ── Split and display segments when the button is clicked ─────────────────────
def on_split_clicked(_):
    with out_area:
        clear_output(wait=True)
        if not uploader.value:
            print("⚠️  Please upload an audio file first.")
            return

        uploaded  = list(uploader.value.values())[0]
        fname     = list(uploader.value.keys())[0]
        ext       = os.path.splitext(fname)[1]
        raw_bytes = bytes(uploaded['content'])

        # Write to a temp file for the pipeline
        tmp = tempfile.NamedTemporaryFile(suffix=ext, delete=False)
        tmp.write(raw_bytes)
        tmp.flush()
        tmp_path = tmp.name
        tmp.close()

        try:
            saved = split_audio(tmp_path)
        except Exception as e:
            print(f"❌ Error during split: {e}")
            return
        finally:
            os.unlink(tmp_path)   # safe to clean up — split_audio saves its own WAVs

        print("\n── 🔊 Segments ──────────────────────────────────────")
        for i, seg_path in enumerate(saved):
            data, sr = sf.read(seg_path)
            dur      = len(data) / sr
            display(HTML(
                f"<b>Segment {i+1}</b> &nbsp;|&nbsp; "
                f"{dur:.2f} s &nbsp;|&nbsp; {os.path.basename(seg_path)}"
            ))
            display(Audio(data=data, rate=sr, autoplay=False))

run_btn.on_click(on_split_clicked)

display(widgets.VBox([
    widgets.HTML(
        "<h3>🎙️ VAD Audio Splitter</h3>"
        "<p>1. Upload → 2. Listen to original → 3. Click Split → 4. Listen to segments</p>"
    ),
    uploader,
    original_out,                           # ← original file player (appears on upload)
    widgets.HTML("<hr style='margin:8px 0'>"),
    run_btn,
    out_area,                               # ← split segments (appear after clicking Split)
]))
